######################################################################
# Automatically generated by qmake (1.07a) Fri Oct 4 14:56:24 2013
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += fsgui.h genericclient.h setupgui.h utility.h wp_ll.h
SOURCES += fsgui.cpp \
           genericclient.cpp \
           main.cpp \
           setupgui.cpp \
           utility.cpp \
           wp_ll.cpp
